language: ruby
rvm:
  - 2
before_install:
  - gem source -u
  - gem uninstall -i /home/travis/.rvm/gems/ruby-2.5.1@global -x bundler
  - gem install bundler -v 1.16.0
before_script:
  - cp ./config/config.{example,yml}
  - cp ./config/database.{travis,yml}
  - cp ./certs/app_cert.{example,pem}
  - cp ./certs/app_key.{example,pem}
  - mysql -e 'create database registrations_test;'
script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:migrate db:test:prepare
  - bundle exec rake ci
bundler_args: --without development production

