language: ruby
rvm:
  - 1.9.3
before_install:
  - gem source -u
before_script:
  - cp ./config/config.{example,yml}
  - cp ./config/database.{travis,yml}
  - cp ./certs/app_cert.{example,pem}
  - cp ./certs/app_key.{example,pem}
  - cp ./certs/paypal_cert.{example,pem}
  - mysql -e 'create database registrations_test;'
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake spec
bundler_args: --without development production assets
