dist: trusty
sudo: required
language: ruby
cache: bundler
rvm:
  - 2.6.4
before_install:
  - gem update --system
  - gem install bundler:1.17.3
services:
  - mysql
before_script:
  - cp ./config/config.{example,yml}
  - cp ./config/database.{travis,yml}
  - cp ./certs/app_cert.{example,pem}
  - cp ./certs/app_key.{example,pem}
  - mysql -e 'create database registrations_test;'
script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:migrate db:test:prepare
  - bundle exec rake ci
bundler_args: --without development production
