language: ruby
rvm:
  - 1.9.1
before_script:
  - cp ./config/config.{example,yml}
  - cp ./config/database.{travis,yml}
  - mysql -e 'create database registrations_test;'
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake ci
bundler_args: --local --without development production assets
