version: '3.7'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: registrations_db
      MYSQL_PASSWORD: registrations_db
      MYSQL_DATABASE: agilebrazil_development
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
      context: .
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
    depends_on:
      - db

volumes:
  mysql-data: